### ISSUE TITLE
using rowClassNameGetter() to use classes with different backgrounds

### ISSUE THREAD

**Issue by Axbon** [facebook/fixed-data-table#43] opened 2015-02-17 09:30 UTC
This was interesting. I use the rowClassNameGetter, which basically returns one of the following class names randomly for each row:  [ 'red', 'green', 'yellow' ]

Then adding css style with background-color, as an example:

.red .public_fixedDataTableCell_main {
  background-color: red;
}

Now try scrolling, warning for epileptics, it flickers/blinks and goes bananas, I suspect this has todo with your scrolling magic :). It does not happen if you simply change the colors of the standard highlighted/normal rows, it has something todo with the randomness, that some rows are color X but not others. Not sure if this is working as intended or if it should be considered a bug. 

Anyway I suppose it would be useful to change colors of rows depending on some condition X.

**Comment by ofersadgat** [comment] 2015-02-17 20:15
No, what is happening is that the row is being requested multiple times and since you randomly select a color when the row is requested, it changes colors unpredictably. (or at least that is my best theory).

**Comment by pieterv** [comment] 2015-02-17 20:26
@ofersadgat that is correct, you will need to use the row index as the seed for your random number generator. Or just use some like the modulos operator: `return colors[index % 3]` which will be stable.

**Comment by pieterv** [comment] 2015-02-21 03:32
Closing this out since its not really something we can "fix" and is intended behavior :)

**Closed by pieterv** 2015-02-21 03:32 UTC

**Comment by Axbon** [comment] 2015-02-22 09:16
Yep, reasonable, thanks for the info! :)
