### ISSUE TITLE
The resize guide is in the wrong position for RTL layouts

### ISSUE THREAD

**Issue by gillesruppert** [facebook/fixed-data-table#167] opened 2015-06-05 22:26 UTC
When the table is used in a RTL layout, the resize guide is in the wrong position as the values passed to it currently make it impossible to calculate the correct position.

![screen shot 2015-06-05 at 3 25 00 pm](https://cloud.githubusercontent.com/assets/153925/8016356/46b9e7fc-0b97-11e5-87a6-8aa8e31a11cf.png)

**Comment by ehzhang** [comment] 2015-06-10 18:26
Hi!

Thanks for bringing up this bug. Can you explain how you came across it, and the steps to reproduce it?

In the examples, I've tried adding the text-align: right; property to both the table and the container, as well as set the Column *align* property to right, but the resize guide appears to be working correctly.

**Comment by gillesruppert** [comment] 2015-06-11 01:34
@ehzhang They way I was able to reproduce the issue was by just adding `dir=RTL` on the html element of the example. I just double-checked now and can't reproduce the issue. I will have a look through the commits to see what could have fixed it.

**Comment by ehzhang** [comment] 2015-06-12 17:13
@gillesruppert so far, I've been unable to reproduce this bug in Firefox, Opera, Safari, Chrome, and IE. I'm going to be closing this issue, but feel free to open it again if you encounter this bug again!

**Closed by ehzhang** 2015-06-12 17:13 UTC

**Comment by gillesruppert** [comment] 2015-06-12 17:57
@ehzhang yep. I couldn't reproduce it either anymore. I'm just happy I took the screenshot, proof that I'm not just seeing things :smile:

**Comment by bartvde** [comment] 2015-07-02 12:37
I am actually seeing this as well.

![screen shot 2015-07-02 at 14 36 51](https://cloud.githubusercontent.com/assets/319678/8477099/ccbc48be-20c7-11e5-9768-3a41f7028d0f.png)

**Comment by bartvde** [comment] 2015-07-02 12:39
if I resize the second column, it seems the position is 100 px (column width) off exactly (e.g. width 97 px instead 197 px).

**Comment by bartvde** [comment] 2015-07-02 12:49
actually it seems the issue is that column resize is not hidden after the move

**Comment by bartvde** [comment] 2015-07-02 12:53
at this my own fault, I need to implement ```isColumnResizing```

**Comment by zekedroid** [comment] 2017-03-08 19:40
Was fighting with this issue for many hours as well. Turns out just setting `isColumnResizing={false}` fixes it. Not sure where in the documentation this was noted though, glad this Issue was brought up
