### ISSUE TITLE
process is not defined.

### ISSUE THREAD

**Issue by jalateras** [facebook/fixed-data-table#42] opened 2015-02-16 00:54 UTC
I am using fixed-data-table v0.1.0 with react 0.12.2 and i get the following error in the browser

```
Uncaught ReferenceError: process is not defined18../ExecutionEnvironment @ FixedDataTableRoot.js:14s @ _prelude.js:1(anonymous function) @ _prelude.js:156../internal/FixedDataTableRoot @ main.js:1s @ _prelude.js:1(anonymous function) @ _prelude.js:14.fixed-data-table @ ratings.js:7s @ _prelude.js:1(anonymous function) @ _prelude.js:11../footer @ app.js:10s @ _prelude.js:1e @ _prelude.js:1(anonymous function) @ _prelude.js:1
```

Here is the react component, which uses the table, which is just code from the samples.

```
'use strict';

var React = require('react');
var {Table, Column} = require('fixed-data-table');

var rows = [
  ['a1', 'b1', 'c1'],
  ['a2', 'b2', 'c2'],
  ['a3', 'b3', 'c3']
];

var Ratings = React.create({
  getInitialState() {
    return {
      data: rows
    }
  },

  render: function() {
    return (
      <Table
        rowHeight={50}
        rowGetter={this.state.data}
        rowsCount={this.state.data.length}
        width={5000}
        height={5000}
        headerHeight={50}>
        <Column
          label="Col 1"
          width={3000}
          dataKey={0}
          />
        <Column
          label="Col 2"
          width={2000}
          dataKey={1}
          />
      </Table>
    );
  }
});

module.exports = Ratings;
```

and here is the usage

```
'use strict';

var React = require('react');
var Router = require('react-router');
var {DefaultRoute, Link, NotFoundRoute, Route, RouteHandler} = Router;
var {Panel} = require('react-bootstrap');

var Header = require('./header');
var Footer = require('./footer');
var Ratings = require('./ratings');

var App = React.createClass({
  getInitialState() {
    return {
    };
  },

  componentWillMount() {
  },

  componentWillUnmount() {
  },

  render() {
    return (
        <div>
          <Ratings />
        </div>
    );
  }
});

var NotFound = React.createClass({
  render() {
    return (
      <h2>Not found</h2>
    );
  }
});

var routes =
  <Route name="app" path="/" handler={App}>
    <DefaultRoute handler={NotFound}/>
    <NotFoundRoute handler={NotFound}/>
  </Route>;

Router.run(routes, function(Handler, state) {
  React.render(<Handler params={state.params} query={state.query}/>, document.getElementById('app'));
}
```

Any ideas?

**Comment by jalateras** [comment] 2015-02-16 01:27
I am also using gulp and browserify.

**Comment by ofersadgat** [comment] 2015-02-17 20:12
rowGetter={this.state.data}

rowGetter is a function like (from the example):

    function rowGetter(rowIndex) {
      return rows[rowIndex];
    }

**Comment by pieterv** [comment] 2015-02-17 20:21
Hey @jalateras, @ofersadgat was right the [`rowGetter`](http://facebook.github.io/fixed-data-table/api-table.html#-rowgetter-required-) needs to be a function. Check to see if that fixes it, if not you will need to look into your browserify config, `process` is a global in node which we use to check the environment type (dev or production), browserify normally defines this for you but maybe you have that turned off, maybe check your browserify `detectGlobals` config.

Im going to close this out since its not a bug in the table per se, but let us know if you can't figure it out.

**Closed by pieterv** 2015-02-17 20:21 UTC
